### ISSUE TITLE
Compile failure on storage on OSX build

### ISSUE THREAD

**Issue by doolin** [copperspice/cs_string#1]
Not sure where else to put this information, feel free to just close it if its in the wrong place.

---

## Here's what's installed

12:10:13 doolin@inventium:~/src/cs_string (git:master:bf347f4)  ruby-2.4.1
$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

---

## Here's the build output

$ make check
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-am
/Applications/Xcode.app/Contents/Developer/usr/bin/make  bin/test
g++ -DPACKAGE_NAME=\"cs_string\" -DPACKAGE_TARNAME=\"cs_string\" -DPACKAGE_VERSION=\"1.0.0\" -DPACKAGE_STRING=\"cs_string\ 1.0.0\" -DPACKAGE_BUGREPORT=\"info@copperspice.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"cs_string\" -DVERSION=\"1.0.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DSIZEOF_SIZE_T=8     -DQT_SHARED -I./src -DCS_STRING_ALLOW_UNSAFE -g -O2 -std=c++11 -MT test/bin_test-main.o -MD -MP -MF test/.deps/bin_test-main.Tpo -c -o test/bin_test-main.o `test -f 'test/main.cpp' || echo './'`test/main.cpp
test/main.cpp:100:28: error: character too large for enclosing character literal type
   CsString::CsChar c127 = '¿';
                           ^
test/main.cpp:104:28: error: character too large for enclosing character literal type
   CsString::CsChar c256 = '↴';
                           ^
test/main.cpp:110:26: error: character too large for enclosing character literal type
   CsString::CsChar cX = '𝅘𝅥𝅮';
                         ^
3 errors generated.
make[2]: *** [test/bin_test-main.o] Error 1
make[1]: *** [check-am] Error 2
make: *** [check] Error 2

---

## Remarks

Given the structure of `test_o2`, it might be worthwhile separating these cases (`CsString::CsChar c127 = '¿';`) from the `CsString::CsChar u127 = UCHAR('¿');`. That is, collect the known bogosity into its own test.

**Comment by doolin** [comment]
gcc 7.1 installed on OSX using brew compiles (we won't discuss linking at this moment).

Looking at xcode docs now.

**Comment by agserm** [comment]
Unable to repeat with supported platforms. Feel free to reopen if the issue is still present.
