### ISSUE TITLE
Request for Discussions Section

### ISSUE THREAD

**Issue by matryoshkahacking** [copperspice/cs_string#10]
Hi I know you by my teacher I am happy to know you are there

Could you please open a Discussion Section as a quick and safe solution for learning your projects ?

See you there

**Comment by bgeller** [comment]
Github is a more of a place for contributors and discussing changes to a particular library. If you have questions about CopperSpice we suggest checking out our CopperSpice forums.  

https://forum.copperspice.com

Thank you so much for your interest in our work!

**Comment by matryoshkahacking** [comment]
Thanks see you there
