### ISSUE TITLE
Documentation for constData() wrong?

### ISSUE THREAD

**Issue by PDHCoder** [copperspice/cs_string#12]
There seems to be an error in the documentation of the constData() method: it should have return type "const typename E::storage_unit *" and not "void".

From https://www.copperspice.com/docs/cs_string/class_csstring_1_1csbasicstring.html#ac353b4a5bfcdfde79571314d373fbd04

template<typename E, typename A = std::allocator<typename E::storage_unit>>
void CsString::CsBasicString< E, A >::constData() const

Returns a pointer to the null terminated data stored in this CsBasicString. The pointer is valid until the string is modified.

**Comment by bgeller** [comment]
Just uploaded new CsString documentation.
