### ISSUE TITLE
CsStringView dangling pointer?

### ISSUE THREAD

**Issue by ThomasKrenn** [copperspice/cs_string#5]
Over here:
https://en.cppreference.com/w/cpp/string/basic_string_view
they say:

`
std::string_view good("a string literal");   // OK: "good" points to a static array
std::string_view bad("a temporary string"s); // "bad" holds a dangling pointer
`
The first example is not working with CsStringView.

**Comment by bgeller** [comment]
The API for `std::string_view` is not compatible with `CsString::CsStringView.` Looking at their examples is interesting but may not always be valid.  

These two examples use the variables _good_ and _bad_ and you mentioned the first example "is not working with CsStringView".  Did you receive an error or warning while compiling? If so, please let us know which error or warning and what it said. 

Barbara

**Comment by ThomasKrenn** [comment]
Did you receive an error or warning while compiling?
No.

// The code below calls CsStringView ctor with a temporary CsBasicString.
CsString::CsStringView text( "a string literal");

I close the issue. If the CsStringView API allows error prone code or should be compatible with string_view is another discussion.

**Comment by agserm** [comment]
Thank you for raising this issue. 

We agree that constructing a stringview from a temporary is not always safe, but there are some cases where it is valid. The standard string_view class always allows constructing from a temporary. The team has decided that deleting this constructor is a good idea, however we are adding a way to do this operation when needed. Right now we are leaning towards calling this operation `make_view`.
