### ISSUE TITLE
Inconsistent 'size_type' and 'int' usage

### ISSUE THREAD

**Issue by ThomasKrenn** [copperspice/cs_string#6]
MSVC warnings:
'argument': conversion from 'CsString::CsStringIterator<E,A>::size_type' to 'int'

'walk' takes an int as first argument.
E.g. here:
`template <typename E, typename A>
CsStringIterator<E,A> &CsStringIterator<E,A>::operator+=(size_type n)
{
   m_iter += E::walk(n, m_iter);
   return *this;
}`

in 

`
walk(int len, std::vector<storage_unit>::const_iterator iter)
`

**Comment by agserm** [comment]
For reproducibility, can you tell us what warnings you had turned on?

**Comment by ThomasKrenn** [comment]
The default MSVC warning level is /W3. 
The warning is:

` 
warning C4244: 'argument': conversion from 'CsString::CsStringIterator<E,A>::size_type' to 'int', possible loss of data
`
To fix it change in cs_encoding.h
the line:
static int walk(int len, std::vector<storage_unit>::const_iterator iter)
to
static int walk(size_t len, std::vector<storage_unit>::const_iterator iter)


BTW: usually also GCC should generate a warning for implicit conversions that may alter a value.

**Comment by agserm** [comment]
These warnings are resolved as part of aee7bd5. Thanks for reporting this.
