### ISSUE TITLE
string 1.3.1

### ISSUE THREAD

**Issue by ericLemanissier** [copperspice/cs_string#9]
Current cmake file indicates [1.3.1](https://github.com/copperspice/cs_string/blob/master/CMakeLists.txt#L10-L12) but there is no tag on this repository
Do you expect to release a new version of string at some point ?

**Comment by agserm** [comment]
We just released 1.3.1 10 days ago, we do not tag releases on this project.

**Comment by ericLemanissier** [comment]
@agserm where can we get a reliable link to the sources of a given version ?
